name: fake_firebase_remote_config
description: Fake Firebase Remote Config for use during Flutter unit & widget tests.
version: 2.1.0
homepage: https://philippbauer.me/
repository: https://github.com/CiriousJoker/fake_firebase_remote_config

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ">= 0.0.1 <4.0.0"
  firebase_remote_config: ">=4.0.0 <6.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
